language: c++

before_install:
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - sudo apt-get install g++-multilib gcc-multilib
  - sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev -y
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - git clone https://github.com/openfl/openfl ~/openfl --depth 1
  - haxelib dev openfl ~/openfl
  - git clone https://github.com/openfl/lime ~/lime --depth 1
  - haxelib dev lime ~/lime
  - git clone https://github.com/openfl/lime-tools ~/lime-tools --depth 1
  - haxelib dev lime-tools ~/lime-tools
  - git clone https://github.com/haxenme/nme ~/nme --depth 1
  - haxelib dev nme ~/nme
  - git clone https://github.com/haxenme/nme-dev ~/nme-dev --depth 1
  - haxelib dev nme-dev ~/nme-dev
  - haxelib install hxcpp
  - haxelib install format
  - haxelib install svg
  - haxelib install munit
  - git clone https://github.com/openfl/openfl-validation ~/openfl-validation
  - haxelib dev openfl $(pwd)
  - haxelib run lime rebuild linux,tools
  - haxelib remove openfl-native

script:
  - haxelib run lime build ~/openfl-validation flash
