language: c++

before_install:
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - sudo apt-get install g++-multilib gcc-multilib
  - sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev -y
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib git hxlibc https://github.com/openfl/hxlibc
  - haxelib git hxtools https://github.com/openfl/hxtools
  - haxelib git openfl-native https://github.com/openfl/openfl-native
  - haxelib git lime https://github.com/openfl/lime
  - haxelib git lime-build https://github.com/openfl/lime-build
  - haxelib install format
  - haxelib install svg
  - haxelib install munit
  - git clone https://github.com/openfl/openfl-validation ~/openfl-validation
  - haxelib dev openfl $(pwd)
  - haxelib run openfl rebuild linux,tools
  - haxelib remove openfl-native
  - haxelib remove lime

script:
  - haxelib run openfl build ~/openfl-validation flash
