language: c++

before_install:
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib git hxlibc https://github.com/openfl/hxlibc
  - haxelib git hxtools https://github.com/openfl/hxtools
  - haxelib git openfl-native https://github.com/openfl/openfl-native
  - haxelib git openfl-native-dev https://github.com/openfl/openfl-native-dev
  - haxelib install format
  - haxelib install svg
  - haxelib install munit
  - git clone https://github.com/openfl/openfl-validation ~/openfl-validation
  - haxelib dev openfl $(pwd)
  - haxelib run openfl rebuild linux,tools
  - haxelib remove openfl-native

script:
  - haxelib run openfl build ~/openfl-validation flash
