language: c++

before_install:
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install openfl-tools
  - haxelib install munit
  - git clone https://github.com/openfl/openfl-validation ~/openfl-validation
  - haxelib dev openfl $(pwd)

script:
  - haxelib run openfl build ~/openfl-validation flash
